# config.yaml
listen: ":8080"

# If you're too scared to use it on your server, you can try it out with online dummy response servers.
# Just point the upstream to one.

# Example:
# upstream: "https://jsonplaceholder.typicode.com"

upstream: ""

# Chaos configuration
chaos:
  error_rate: 0
  error_code: 503
  drop_rate: 0

  latency: "200ms"

  # `latency_min` and `latency_max` will be ignored when `latency` is set to a non-zero value

  # Plaease make sure that `latency_min` <= `latency_max`
  # latency_min: "0ms"
  # latency_max: "1000ms"

  corrupt_rate: 0